name: Canary-CentOS

on:
  schedule:
    - cron:  '0 16 * * *'
  workflow_dispatch:

jobs:
  canary-test-centos:
    if: github.repository == 'aws-samples/djl-demo'
    runs-on: ubuntu-latest
    container: ${{ matrix.images }}
    strategy:
      matrix:
        images: ["centos:7"]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set AWS_REGION
        run: echo '::set-env name=AWS_REGION::us-east-1'
      - name: Test MXNet
        run: |
          cd canary
          ./gradlew clean run
          rm -rf ~/.mxnet ~/.djl.ai
          DJL_ENGINE=mxnet-native-mkl ./gradlew clean run
          rm -rf ~/.mxnet ~/.djl.ai
      - name: Test PyTorch
        run: |
          cd canary
          DJL_ENGINE=pytorch-native-cpu-precxx11 ./gradlew clean run
          rm -rf ~/.pytorch ~/.djl.ai
      - name: Test TensorFlow
        run: |
          cd canary
          DJL_ENGINE=tensorflow-native-auto ./gradlew clean run

