name: Canary-Windows

on:
  schedule:
    - cron:  '0 14 * * *'
  workflow_dispatch:

jobs:
  canary-test-windows:
    if: github.repository == 'aws-samples/djl-demo'
    runs-on: windows-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test MXNet
        working-directory: canary
        run: |
          cmd /c ".\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
          # cmd /c "set DJL_ENGINE=mxnet-native-mkl&& .\gradlew.bat clean run"
          # cmd /c "rd /s /q %userprofile%\.djl.ai"
      - name: Test PyTorch
        working-directory: canary
        run: |
          cmd /c "set DJL_ENGINE=pytorch-native-auto&& .\gradlew.bat clean run"
          cmd /c "rd /s /q %userprofile%\.djl.ai"
          cmd /c "set DJL_ENGINE=pytorch-native-cpu&& .\gradlew.bat clean run"
      - name: Test TensorFlow
        working-directory: canary
        run: |
          cmd /c "set DJL_ENGINE=tensorflow-native-auto&& .\gradlew.bat clean run"
