name: nightly build

on:
  # To trigger this workflow manually, you can use the following curl command:
  # curl -XPOST -u "USERNAME:PERSONAL_TOKEN" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/awslabs/djl-demo/dispatches --data '{"event_type": "nightly-build"}'

  # Make sure you create your personal token with repo access. Follow steps in
  # https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
  # to create your personal token.
  repository_dispatch:
    types: [nightly-build]
  schedule:
    - cron:  '0 10 * * *'

jobs:
  documentation:
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: install Python Dependencies
        run: pip3 install mkdocs mkdocs-exclude mknotebooks mkdocs-material jupyter Pygments
      - name: clone DJL repo to access the DJL parent dir
        run: git clone https://github.com/aws-samples/djl-demo djl_demo_tmp
      - name: build docs
        run: |
          cd djl_demo_tmp/docs
          mkdocs build --site-dir ../../site
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync site s3://djl-ai/documentation/demo/nightly --delete
